### ISSUE TITLE
Need to update Metadata?

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaMatrices/LowRankApprox.jl#5]
The Travis build is currently unknown.

https://travis-ci.org/klho/LowRankApprox.jl

Also, @dlfivefifty, attobot has made tagging packages as simple as pointing and clicking. https://github.com/attobot/attobot

**Comment by klho** [comment]
Commit d39c4d2d2e400d55b53209fbc12556320059d81e fixes the Travis link.

**Comment by dlfivefifty** [comment]
It’s now tagged
